### ISSUE TITLE
The htmlentities issue still exists with single quote

### ISSUE THREAD

**Issue by clarkwinkelmann** [askvortsov1/rich-icu-message-formatter#2]
The recent PR fixes the htmlentities issue for all characters except single quote

https://github.com/askvortsov1/rich-icu-message-formatter/blob/18330c61b304e1f973b28362855013d9bdc891ab/source/utilities.js#L238

`&#39;` should be `&#039;`

**Comment by askvortsov1** [comment]
Argh this is what I get for using single-quoted strings in my test cases and forgetting to include single quotes in the tests.

**Comment by askvortsov1** [comment]
Fixed in 016b35fc803ac7cec368a9283775f569fe641807
